version: '2'
services:

 java:
  image: java/example
  build:
   context: .
  ports:
   - "8080:8080"

  volumes:
   - ./application:/application
   - gradle:/root/.gradle
   - gradle:/application/.gradle

volumes:
 gradle:
